### ISSUE TITLE
Bug with adding to arrays on objects

### ISSUE THREAD

**Issue by Symmettry** [face-hh/bussin#58]
let a = { a: [ 0, 1 ], b: 2 };

a.a[0] += 2

println(a)

will result in

{ a: [ 0, 1 ], b: 2, undefined: false }

instead of

{ a: [ 2, 1 ], b: 2 }

(this is not a bug with +=, as doing a.a[0] = a.a[0] + 2 will result in the same thing)

**Comment by Symmettry** [comment]
Doing

let a = { a: [ 0, 1 ], b: 2 };

let c = a.a;
c[0] += 2

works tho. it appears doing object.array[] will be trying to like set "array[]" of "object" instead of modifying "array" of "object"

**Comment by Symmettry** [comment]
Doing a.a[0] will result in [0, 1] instead of 0.

**Comment by Symmettry** [comment]
Caught the culprit probably.

if (expr.object.kind === 'MemberExpr') return this.lookupOrMutObject(expr.object as MemberExpr, value, expr.property as Identifier);

This here will fully ignore the previous portion.

so

a.b.c will see the object kind is member expr (a.b.) and then it will lookup "b" on "a" and return that, but it fully skips "c"

**Comment by Symmettry** [comment]
ok so i fixed a.b.c but i don't know the problem with a.b[c]

**Comment by Symmettry** [comment]
fixed that. #55
